# Generated by Django 5.0.6 on 2024-07-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
